apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/skabashnyuk/centos-bootc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression:
      event == "pull_request" && target_branch
      == "main" && ! "docs/***".pathChanged()
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: skabashn-centos-bootc
    appstudio.openshift.io/component: fedora-bootc
    pipelines.appstudio.openshift.io/type: build
  name: fedora-bootc-on-pull-request
  namespace: rhtap-spi-tenant
spec:
  params:
    - name: image-file
      value: fedora-bootc.yaml
    - name: git-url
      value: "{{repo_url}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/rhtap-spi-tenant/skabashn-centos-bootc/fedora-bootc:on-pr-{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: "{{revision}}"
    - name: config-file
      value: "fedora-bootc-config.json"
  pipelineRef:
    name: ostree-build
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: workspace-arm64
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
        status: {}
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
