name: Build Image

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest

    container:
      image: quay.io/centos-bootc/bootc-image-builder:latest
      options: --privileged

    # Yes, this is a one-element matrix, but we may add c10s in the future soon
    strategy:
      matrix:
        os: [centos]
        include:
          - os: centos
            version: stream9

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Build
        run: |
          rpm-ostree compose image --format=ociarchive \
          --initialize ${{ matrix.os }}-bootc.yaml dest.oci-archive
